id: I14313CFD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T00:34:07+00:00'
last_modified: '2022-06-08T13:21:40.480443+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21980
  title: སི་ཁྲོན་མཛོད་དགེའི་གླིང་བ་དགོན་གྲོང་གི་ལོ་རྒྱུས་རྒྱས་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    023A:
      image_group_id: I1GS105531
      title: ''
      total_pages: 288
      order: 1
      base_file: 023A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
