id: P010406
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-19 20:48:07.122953
source_metadata:
  id: bdr:W21980
  title: སི་ཁྲོན་མཛོད་དགེའི་གླིང་བ་དགོན་གྲོང་གི་ལོ་རྒྱུས་རྒྱས་པ།
  author: ''
  volumes:
    63fba00e906843fb8b91f6c91833ae93:
      image_group_id: I1GS105531
      title: ''
      volume_number: 1
      total_pages: 288
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
