id: P010406
initial_creation_type: ocr
source_metadata:
  id: bdr:W21980
  title: སི་ཁྲོན་མཛོད་དགེའི་གླིང་བ་དགོན་གྲོང་གི་ལོ་རྒྱུས་རྒྱས་པ།
  author: ''
  volumes:
    63fba00e906843fb8b91f6c91833ae93:
      image_group_id: I1GS105531
      title: ''
      volume_number: 1
      total_pages: 288
      base_file: v001.txt
